@startmindmap
* 无继承
** 对象类型
*** 值类型
**** null
**** value
*** 简单对象
*** 泛型对象
** 访问控制
*** private
*** protected
*** public
*** package（按 public 处理）

* 有继承
** 属性完全来自本类
** 属性部分来自本类、部分来自父类
** 属性全部来自父类
*** 属性全部来自某级父类
*** 属性部分来自第 n 级父类，部分来自更高层的父类


@endmindmap