package com.xyzwps.lib.jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public interface TransactionContext extends AutoCloseable {

    ResultSetToBean rs2b();

    Statement createStatement() throws SQLException ;

    PreparedStatement prepareStatement(String sql, boolean returnAutoGeneratedKeys) throws SQLException;

    PreparedStatement prepareStatement(String sql) throws SQLException;

    static TransactionContext create(Connection conn, ResultSetToBean rs2b) {
        return new SimpleTransactionContext(conn, rs2b);
    }
}
