package com.xyzwps.lib.jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public final class TX {

    private final Connection conn;

    final ResultSetToBean rs2b;

    TX(Connection conn, ResultSetToBean rs2b) {
        this.conn = conn;
        this.rs2b = rs2b;
    }


    public Statement createStatement() throws SQLException {
        return conn.createStatement();
    }

    public PreparedStatement prepareStatement(String sql, boolean returnAutoGeneratedKeys) throws SQLException {
        return conn.prepareStatement(sql, returnAutoGeneratedKeys ? Statement.RETURN_GENERATED_KEYS : Statement.NO_GENERATED_KEYS);
    }

}
